#!/bin/bash
set -e

CURRENTDIR=$(pwd)
HOSTNAME="si_node"

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Update all packages
git submodule update --init --recursive

# Change the hostname
sed -i "s/raspberrypi/${HOSTNAME}/g" /etc/hosts
echo $HOSTNAME > /etc/hostname
echo $HOSTNAME > /boot/hostnames
echo "Hostname changed to $HOSTNAME"

# Disable the screensave
echo "@xset s noblank" > /etc/xdg/lxsession/LXDE/autostart
echo "@xset s off" > /etc/xdg/lxsession/LXDE/autostart
echo "@xset -dpms" > /etc/xdg/lxsession/LXDE/autostart
echo "xserver-command=X -s 0 -dpms" > /etc/lightdm/lightdm.conf

# Install social interaction
cd $CURRENTDIR/components/social_interaction
exec ./INSTALL

ln -s $CURRENTDIR/START /etc/init.d/willy
update-rc.d willy enable

cd $CURRENTDIR
