#!/bin/bash
set -e

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

git submodule update --init --recursive

# Install social interaction
exec "components/social_interaction/INSTALL"
