#!/bin/bash
### BEGIN INIT INFO
# Provides: willy
# Required-Start: $all
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description:  Enable willy processes
### END INIT INFO

WOKRING_DIR="/opt/willy"
cd $WOKRING_DIR

case "$1" in
start)
  cd $WOKRING_DIR/components/social_interaction
  exec ./START start
  ;;
stop)
  cd $WOKRING_DIR/components/social_interaction
  exec START stop
  ;;
restart)
  $0 stop
  $0 start
  ;;
*)
  echo "Usage: $0 {start|stop|restart}"
esac

exit 0
